name: seguro
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  url_launcher: ^6.0.2
  font_awesome_flutter: ^10.2.0
  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0
  http: ^1.2.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/fondo1.jpg
    - assets/images/Info1.jpg
    - assets/images/Info2.jpg
    - assets/images/Info3.jpg
    - assets/o1.png
    - assets/o2.png
    - assets/o3.png
    - assets/o4.png
    - assets/o5.png
    - assets/o6.png
    - assets/p1.jpg
    - assets/p2.jpg
    - assets/p3.jpg
    - assets/poleranegra.jpg
    - assets/polo.jpg
    - assets/pantalon.png
    - assets/zapatos.jpg